# Generated by Django 4.2.6 on 2023-11-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('preis', models.FloatField(verbose_name='Preis')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestelldatum', models.DateTimeField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('erledigt', models.BooleanField(blank=True, default=False, null=True, verbose_name='Erledigt')),
                ('auftrags_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auftrags ID')),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kunde', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
            },
        ),
        migrations.CreateModel(
            name='BestellteArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.IntegerField(blank=True, default=0, null=True, verbose_name='Menge')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('artikel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.artikel', verbose_name='Artikel')),
                ('bestellung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.bestellung', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Bestellter Artikel',
                'verbose_name_plural': 'Bestellte Artikel',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straße', models.CharField(blank=True, max_length=200, null=True, verbose_name='Straße & Hausnummer')),
                ('plz', models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ')),
                ('stadt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stadt')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Adresse')),
                ('bestellung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.bestellung', verbose_name='Bestellung')),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kunde', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
    ]
