# Generated by Django 4.2.6 on 2023-11-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_artikel_bestellung_bestellteartikel_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='bestellung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.bestellung', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='kunde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kunde', verbose_name='Kunde'),
        ),
    ]
